# Default colors
set-option -g @c-primary-bg "#161821"
set-option -g @c-primary-fg "#c6c8d1"

# Cursor colors
set-option -g @c-cursor-text "#161821"
set-option -g @c-cursor-cursor "#c6c8d1"

# Selection colors
set-option -g @c-selection-text ""
set-option -g @c-selection-bg "#272c42"

# Normal colors
set-option -g @c-normal-black "#1e2132"
set-option -g @c-normal-red "#e27878"
set-option -g @c-normal-green "#b4be82"
set-option -g @c-normal-yellow "#e2a478"
set-option -g @c-normal-blue "#84a0c6"
set-option -g @c-normal-magenta "#1093c7"
set-option -g @c-normal-cyan "#89b8c2"
set-option -g @c-normal-white "#c6c8d1"

# Bright colors
set-option -g @c-bright-black "#6b7089"
set-option -g @c-bright-red "#e98989"
set-option -g @c-bright-green "#c0ca8e"
set-option -g @c-bright-yellow "#e9b189"
set-option -g @c-bright-blue "#91acd1"
set-option -g @c-bright-magenta "#ada0d3"
set-option -g @c-bright-cyan "#95c4ce"
set-option -g @c-bright-white "#d2d4de"

# Test
set-option -g status-style "bg=#{@c-primary-bg},fg=#{@c-primary-fg}"
