shell = 'zsh'

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[templates]
defer = """{{ hooks?.pre | nl }}{% for file in files %}
zsh-defer source \"{{ file }}\"\n
{% endfor %}{{ hooks?.post | nl }}"""

[plugins.bashcompinit]
inline = 'autoload bashcompinit && zsh-defer bashcompinit'

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['defer']

[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'
apply = ['defer']

[plugins.zsh-abbr]
github = 'olets/zsh-abbr'
apply = ['defer']

[plugins.docker-completion]
remote = "https://raw.githubusercontent.com/docker/cli/refs/heads/master/contrib/completion/zsh/_docker"
apply = ["fpath"]

[plugins.git-completion]
remote = "https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-completion.bash"
apply = ["defer"]

[plugins.aws_completion]
inline = 'zsh-defer complete -C aws_completer aws'

[plugins.dotfiles-sync]
local = '~/.config/zsh/sync'
use = ['*.zsh']
apply = ['source']

[plugins.dotfiles-defer]
local = '~/.config/zsh/defer'
use = ['*.zsh']
apply = ['defer']
