format = """
[░▒▓](#ada0d3)\
$os\
[](bg:#84a0c6 fg:#ada0d3)\
$directory\
[](fg:#84a0c6 bg:#e9b189)\
$git_branch\
$git_status\
[](fg:#e9b189 bg:#6b7089)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#6b7089 bg:#1e2132)\
$time\
[ ](fg:#1e2132)\
\n$character"""

[os]
style = "bg:#ada0d3 fg:#1e2132"
format = "[$symbol]($style)"
disabled = false

[os.symbols]
Alpine = "  "
Arch = "  "
CentOS = "  "
Debian = "  "
Linux = "  "
Macos = "  "
Redhat = "  "
Ubuntu = "  "

[directory]
style = "fg:#1e2132 bg:#84a0c6"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#e9b189"
format = '[[ $symbol $branch ](fg:#1e2132 bg:#e9b189)]($style)'

[git_status]
style = "bg:#e9b189"
format = '[[($all_status$ahead_behind )](fg:#1e2132 bg:#e9b189)]($style)'

[nodejs]
symbol = ""
style = "bg:#6b7089"
format = '[[ $symbol ($version) ](fg:#d2d4de bg:#6b7089)]($style)'

[rust]
symbol = ""
style = "bg:#6b7089"
format = '[[ $symbol ($version) ](fg:#d2d4de bg:#6b7089)]($style)'

[golang]
symbol = ""
style = "bg:#6b7089"
format = '[[ $symbol ($version) ](fg:#d2d4de bg:#6b7089)]($style)'

[php]
symbol = ""
style = "bg:#6b7089"
format = '[[ $symbol ($version) ](fg:#d2d4de bg:#6b7089)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1e2132"
format = '[[  $time ](fg:#a0a9cb bg:#1e2132)]($style)'

[character]
success_symbol = '[❯](bold #b4be82)'
error_symbol = '[❯](bold #e27878)'
vimcmd_symbol = '[❮](bold #ada0d3)'
