format = """
$os\
[ ](fg:#1e2132 bg:#c6c8d1)\
$directory\
[](fg:#c6c8d1 bg:#1e2132)\
$git_branch\
$git_status\
[ ](fg:#6b7089 bg:#1e2132)\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:#6b7089 bg:#1e2132)\
$time\
[ ](fg:#6b7089)\
\n$character"""

[os]
style = "fg:#d2d4de bg:#1e2132"
format = "[$symbol]($style)"
disabled = false

[os.symbols]
Alpine = "  "
Arch = "  "
CentOS = "  "
Debian = "  "
Linux = "  "
Macos = "  "
Redhat = "  "
Ubuntu = "  "

[directory]
style = "fg:#1e2132 bg:#c6c8d1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#1e2132"
format = '[[ $symbol $branch ](fg:#91acd1 bg:#1e2132)]($style)'

[git_status]
style = "bg:#1e2132"
format = '[[($all_status$ahead_behind )](fg:#e2a478 bg:#1e2132)]($style)'

[nodejs]
symbol = ""
style = "bg:#1e2132"
format = '[[ $symbol ($version) ](fg:#6b7089 bg:#1e2132)]($style)'

[rust]
symbol = ""
style = "bg:#1e2132"
format = '[[ $symbol ($version) ](fg:#6b7089 bg:#1e2132)]($style)'

[golang]
symbol = ""
style = "bg:#1e2132"
format = '[[ $symbol ($version) ](fg:#6b7089 bg:#1e2132)]($style)'

[php]
symbol = ""
style = "bg:#1e2132"
format = '[[ $symbol ($version) ](fg:#6b7089 bg:#1e2132)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1e2132"
format = '[[  $time ](fg:#1e2132 bg:#6b7089)]($style)'

[character]
success_symbol = '[❯](bold #b4be82)'
error_symbol = '[❯](bold #e27878)'
vimcmd_symbol = '[❮](bold #ada0d3)'
