# vim: ft=gitconfig
[alias]
  graph = log --graph --date-short --decorate --pretty=format:'%C(yellow)%h%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'
  amend = commit --amend --no-edit
  wdiff = diff --word-diff
  stashes = stash list
  conflicts = diff --name-only --diff-filter=U
