# vim: ft=gitconfig
[core]
  autocrlf = false
  symlinks = true
  editor = nvim

[init]
  defaultBranch = main

[status]
  showUntrackedFiles = all

[commit]
  verbose = true

[diff]
  algorithm = histogram
  colorMoved = plain

[merge]
  conflictStyle = zdiff3

[fetch]
  prune = true

[pull]
  rebase = true

[push]
  default = simple
  followTags = true
  useForceIfIncludes = true
  autoSetupRemote = true

[rebase]
  autoStash = true
  updateRefs = true

[help]
  autocorrect = prompt

