snippets:
  - name: g
    keyword: g
    snippet: git

  - name: yyyymmdd
    keyword: yyyymmdd
    snippet: date "+%Y%m%d"
    evaluate: true
    global: true

  - name: git status
    keyword: gs
    snippet: git status --short --branch

  - name: git commit message
    keyword: gcim
    snippet: git commit -m '{{commit_message}}'

  - name: git add
    keyword: ga
    snippet: git add -u

  - name: "null"
    keyword: "null"
    snippet: ">/dev/null 2>&1"
    context:
      lbuffer: '.+\s'

  - name: branch
    keyword: B
    snippet: git symbolic-ref --short HEAD
    context:
      lbuffer: '^git\s+checkout\s+'
    evaluate: true

  - name: .zshrc
    keyword: zsh.conf
    snippet: $ZDOTDIR/.zshrc
    global: true

  - name: sheldon toml
    keyword: sheldon.conf
    snippet: $XDG_CONFIG_HOME/sheldon/plugins.toml
    global: true

  - name: zeno config.yml
    keyword: zeno.conf
    snippet: $XDG_CONFIG_HOME/zeno/config.yml
    global: true

  - name: nvim
    keyword: v
    snippet: nvim


completions:
  - name: kill signal
    patterns:
      - "^kill -s $"
    sourceCommand: "kill -l | tr ' ' '\\n'"
    options:
      --prompt: "'Kill Signal> '"

  - name: kill pid
    patterns:
      - "^kill( .*)? $"
    excludePatterns:
      - " -[lns] $"
    sourceCommand: "LANG=C ps -ef | sed 1d"
    options:
      --multi: true
      --prompt: "'Kill Process> '"
    callback: "awk '{print $2}'"

  - name: chdir
    patterns:
      - "^cd $"
    sourceCommand: "find . -path '*/.git' -prune -o -maxdepth 5 -type d -print0"
    options:
      --read0: true
      --prompt: "'Chdir> '"
      --preview: "cd {} && ls -a | sed '/^[.]*$/d'"
    callback: "cut -z -c 3-"
    callbackZero: true
