git_protocol: ssh
editor:
prompt: enabled
pager:
aliases:
  create: repo create
  fork: repo fork
  open: repo view --web
  remote: '!gh repo view --json="sshUrl" --jq=".sshUrl" "$(basename "$(git rev-parse --show-toplevel)")"'
  add-remote: '!git remote add origin "$(gh remote)" && git remote show origin'
