# vim: ft=tmux
# Replace Prefix Key
unbind-key C-b
set-option -g prefix C-t

# Reload Settings
bind-key -N "Reload Config" r {
  source-file ${XDG_CONFIG_HOME}/tmux/tmux.conf \;
  display "Config Reloaded."
}

# Select Key-Binding Style Vim Mode
set-option -gw mode-keys vi

# Split pane
bind-key - split-window -v
bind-key _ split-window -v
bind-key \\ split-window -h
bind-key | split-window -h

# Switch pane
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

# Resize pane
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Switch window
bind-key -r p previous-window
bind-key -r n next-window
bind-key -n M-p previous-window
bind-key -n M-n next-window

# Swap window
bind-key -n M-h swap-window -t -1 \; previous-window
bind-key -n M-l swap-window -t +1 \; next-window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Copy mode Key-bindings
bind-key -T copy-mode-vi y { send-keys -X copy-pipe }
bind-key -T copy-mode-vi v { send-keys -X begin-selection }
bind-key -T copy-mode-vi C-v { send-keys -X rectangle-toggle }
bind-key -T copy-mode-vi V { send-keys -X select-line }
bind-key -N "cmode: Move to previous prompt" -T copy-mode-vi [ {
  send-keys -X previous-prompt -o
}
bind-key -N "cmode: Move to next prompt" -T copy-mode-vi ] {
  send-keys -X next-prompt -o
}
