# vim: ft=tmux
## Set history size
set-option -g history-limit 5000

# Enable mouse input
set-option -g mouse on

# Enable clipboard
set-option -s set-clipboard on

# Enable true color
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"
