# Base Settings
source ${XDG_CONFIG_HOME}/tmux/options.conf

# Key Bindings
source ${XDG_CONFIG_HOME}/tmux/key-bindings.conf

# Colorscheme
source ${XDG_CONFIG_HOME}/tmux/themes/iceberg.conf

# Style
source ${XDG_CONFIG_HOME}/tmux/style.conf
