abbr -S v='nvim'
abbr -S g='git'
abbr -S b='bat'
abbr -S venv='source venv/bin/activate'
abbr -S ra='rails'
abbr -S gr='grep'
abbr -S k='kubectl'
abbr -S t='tmux'
abbr -S ta='tmux attach'

# docker
abbr -S d='docker'
abbr -S dps='docker container ls'
abbr -S dimgs='docker image ls'
abbr -S drun='docker container run'
abbr -S dcd='docker compose -d'

# git
abbr -S ga='git add -u'
abbr -S gs='git status --short --branch'
abbr -S gbr='git branch'
abbr -S gci='git commit -v'
abbr -S gcim='git commit -m'
abbr -S gco='git checkout'
abbr -S gcob='git checkout -b'
abbr -S gdf='git diff'
abbr -S gl='git log'
abbr -S ggr='git grep'
abbr -S gul='git pull'
abbr -S gsw='git switch'
abbr -S gush='git push'
abbr -S gget='ghq get'

