name: "setup script test"

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo curl file make
      - name: Install dotfiles
        run: make setup
  centos:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v3
      - name: yum url setting
        run: sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*;
        run: sed-i 's|#baseurl=http://mirror.centos.org/$contentdir/$releasever/$releasever/|baseurl=https://ftp.riken.jp/Linux/centos-vault/7.9.2009/|g' /etc/yum.repos.d/CentOS-Linux-*;
      - name: Install required packages
        run: yum update && yum install -y git sudo curl file make
      - name: Install dotfiles
        run: make setup
  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: apk add git sudo curl file make bash
      - name: Install dotfiles
        run: make setup
  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Update packages
        run: pacman -Syu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm git sudo curl file make
      - name: Install dotfiles
        run: make setup
